name: Build NaivePortScanner For Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: pyinstaller -D -w -n NaivePortScanner --optimize 2 main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NaivePortScanner
          path: dist/NaivePortScanner
